using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.iOS;

public class Spawn : MonoBehaviour
{
    public GameObject flask;
    public GameObject syringe;
    public GameObject litmusPaper;
    public GameObject selectedObject;
    public float maxRayDistance = 30.0f;

    // Start is called before the first frame update
    void Start()
    {
        selectedObject = flask;
    }

    // Update is called once per frame
    void Update()
    {
        var touch = Input.GetTouch(0);
        if (touch.phase == TouchPhase.Began)
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.GetTouch(0).position);
            RaycastHit hit;

            //we'll try to hit one of the plane collider gameobjects that were generated by the plugin
            //effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
            if (Physics.Raycast(ray, out hit, maxRayDistance))
            {
                if (hit.collider.tag == "Surface")
                {
                    GameObject go = Instantiate(selectedObject, hit.point, transform.rotation);
                }
            }

        }
    }

    public void selectFlask()
    {
        selectedObject = flask;
    }

    public void selectSyringe()
    {
        selectedObject = syringe;
    }

    public void selectLitmusPaper()
    {
        selectedObject = litmusPaper;
    }


}