using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.XR.iOS;

public class Spawn : MonoBehaviour
{
    public GameObject flask;
    public GameObject syringe;
    public GameObject litmusPaper;
    public GameObject Base;
    public GameObject selectedObject;
    public GameObject panel;

    public float maxRayDistance = 30.0f;

    // Start is called before the first frame update
    void Start()
    {
        selectedObject = null;
        
    }

    // Update is called once per frame
    void Update()
    {
        if (PlayerPrefs.HasKey("achi"))
        {

        }
        var touch = Input.GetTouch(0);
        if (touch.phase == TouchPhase.Began)
        {
            Ray ray = Camera.main.ScreenPointToRay(touch.position);
            RaycastHit hit;

            //we'll try to hit one of the plane collider gameobjects that were generated by the plugin
            //effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
            if (Physics.Raycast(ray, out hit, maxRayDistance))
            {
                if (hit.collider.tag == "Surface")
                {
                    if (selectedObject != null)
                    {
                        if(selectedObject == syringe)
                        {
                            GameObject go = Instantiate(selectedObject, hit.point + new Vector3(0, 0.05f, 0), transform.rotation);
                        }
                        else
                        {
                            GameObject go = Instantiate(selectedObject, hit.point + new Vector3(0, 0.5f, 0), transform.rotation);
                        }
                       
                        if(selectedObject == flask)
                        {
                            PlayerPrefs.SetInt("test1", 1);
                            Debug.Log("new achievement");
                        }
                        else if (selectedObject == Base)
                        {
                            PlayerPrefs.SetInt("test2", 1);
                            Debug.Log("new achievement");
                        }
                        else if (selectedObject == litmusPaper)
                        {
                            PlayerPrefs.SetInt("test3", 1);
                            Debug.Log("new achievement");
                        }
                        else if (selectedObject == syringe)
                        {
                            PlayerPrefs.SetInt("test4", 1);
                            Debug.Log("new achievement");
                        }
                        selectedObject = null;
                        
                    }
                }
            }

        }
    }

    public void selectFlask()
    {
        selectedObject = flask;
    }

    public void selectSyringe()
    {
        selectedObject = syringe;
    }

    public void selectLitmusPaper()
    {
        selectedObject = litmusPaper;
    }
    public void selectBase()
    {
        selectedObject = Base;
    }

}